### ISSUE TITLE
[Feature request]: Ability to specify filter sets per resource type

### ISSUE THREAD

**Issue by leflings** [Setono/SyliusImagePlugin#20]
### Describe the proposed solution

Ability to specify which resource types applies to which filters.

Say we have both `TaxonImage` and `ProductImage` implement the `ImageInterface` from the plugin both of these would be considered processable resources.

However, you typically has a set of filters that applies only to product images, and another set of filters that applies to taxons. Currently, taxon variants would be generated for all ProductImages, and the other way around, all product variants would be generated for all TaxonImages.

In most cases it might not be a huge problem, since there are often significantly less taxon images than product images, and fewer taxon specific variants than product specific variants, but it is easy to imagine scenarios where this might not be true.

**Comment by leflings** [comment]
From my point of view there are two different ways the configuration format can be expanded to accomodate this information.

Either

a) Resources are specified per variant
b) Variants are specified per resource

## A

```yaml
setono_sylius_image:
    filter_sets:
        app_one:
            resources:
                - 'sylius.product_image'
                - 'sylius.taxon_image'
                - 'app.energy_label_image'
        app_two:
            resources:
                - 'sylius.product_image'
        app_three: ~
```

We could assume that if resources are not specified, we default to all eligible resources (resources that implement the `ImageInterface`)?

Otherwise the `resources` node acts as a 'whitelist'

## B

```yaml
setono_sylius_image:
    resources:
        sylius.product_image: # are dots even allowed in keys?
            - 'app_one'
            - 'app_two'
        sylius.taxon_image:
            - 'app_one'
        app.energy_label_image:
            - 'app_one'
        app.some_other_image: ~
```

The `resources` section could serve two purposes

1) A place to specify which resources the plugin should handle (replacing default behaviour of `ProcessableResourceProvider`?) - this is not necessarily relevant to this issue, but if this config format is chosen, it could be confusing (in this case perhaps rename `resources` key)
2) A place to specify variants per resource type

Similarly to A - `~` would specify "all variants" and otherwise it acts as a whitelist for variants to generate

## Pros / cons

I'm personally in favor of A. Neither format can avoid some repetition.

## Storing info in `Variant`

Regardless of whether approach A or B is chosen, I guess this info should be added on `Variant`.

```php
/** $resources array<array-key, string> */
public array $resources;
```

And then when a decision needs to be made perhaps a service with access to `%sylius.resources%` that can infer the information from a `Variant` and an `ImageInterface`. Something like:

```php
<?

class VariantEligiblityChecker
{
    private array $resources;

    public function __construct(array $resources /* sylius.resource */)
    {
        $this->resources = $resources;
    }

    public function isEligible(ImageInterface $image, Variant $variant): bool
    {
        ....
    }
}
