### ISSUE TITLE
[Bug]: public_processed_path configuration not properly supported

### ISSUE THREAD

**Issue by leflings** [Setono/SyliusImagePlugin#25]
### Plugin version

latest

### Sylius version

1.10

### What happened?

Configuration allows modifying where processed images should be stored:
```yaml
# Default configuration for extension with alias: "setono_sylius_image"
setono_sylius_image:
    # This is the path where processed images are saved in a web context. I.e. if you can access a processed image here:
    # https://example.com/media/image/processed/sylius_shop_large/ae/ef/a7f7d7a3e.jpg,
    # then your public_processed_path should be /media/image/processed. As the name implies the path must be publicly accessible
    public_processed_path: /media/image/processed
```

However, that configuration parameter is only used in configuring the [twig extension](https://github.com/Setono/SyliusImagePlugin/blob/master/src/Resources/config/services/twig.xml#L20)

It is *not* used when setting up the [file system/adapter](https://github.com/Setono/SyliusImagePlugin/blob/master/src/Resources/config/app/config.yaml#L20)
```yaml
knp_gaufrette:
    adapters:
        setono_sylius_image_processed:
            local:
                directory: "%sylius_core.public_dir%/media/image/processed"
                create: true
```

**Comment by leflings** [comment]
There are more errors with this configuration.

It is also not adhered to in the [routing](https://github.com/Setono/SyliusImagePlugin/blob/master/src/Resources/config/routes/global.yaml):
```yaml
setono_sylius_image_shop_render_image:
    path: /media/image/processed/{variant}/{path} # <--- !!! PROBLEM HERE
    methods: [ GET ]
    defaults:
        _controller: setono_sylius_image.controller.action.redirect_non_existing_image_variant
    requirements:
        path: .+ # This allows / in the $path variable
```
