### ISSUE TITLE
[Bug]: Environment variable not found: "CLOUDFLARE_API_TOKEN"

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusImagePlugin#52]
### Plugin version

0.1.3

### Sylius version

1.11

### What happened?

I am trying to install the plugin and I get this error when I have followed the installation instructions. It's because the plugin uses this environment variable when setting up the HTTP client:

```yaml
framework:
    http_client:
        scoped_clients:
            cloudflare.client:
                base_uri: "https://api.cloudflare.com"
                headers:
                    Accept: "application/json"
                    Authorization: 'Bearer %env(CLOUDFLARE_API_TOKEN)%'
```
